### ISSUE TITLE
Whether need to run 100 epochs?

### ISSUE THREAD

**Issue by CheaSim** [hy-struggle/PRGC#4]
![image](https://user-images.githubusercontent.com/31753427/134882459-5bbba0a0-be2c-4199-84a4-23f4ac532d2a.png)
I have run 20 epochs, and the f1 score seems not to be higher. Also, I can not reproduce the same result in NYT as in the paper? So we must run 100 epochs?

**Comment by hy-struggle** [comment]
For fair comparison, we chose the same epochs as Tplinker. In NYT*, we trained 100 epochs and chose the last performance on the validation set, and set rel_threshold=0.2, mat_threshold=0.8 on the test set. You can reproduce the same result when you do the same.

**Comment by CheaSim** [comment]
ok, thanks for your reply.

**Comment by 32209056** [comment]
File "D:/sulisha/HGT-DGL-master/PRGC-main/PRGC-main/train.py", line 224, in <module>
    train_and_evaluate(model, params, ex_params, args.restore_file)
  File "D:/sulisha/HGT-DGL-master/PRGC-main/PRGC-main/train.py", line 153, in train_and_evaluate
    val_metrics, _, _ = evaluate(model, val_loader, params, ex_params, mark='Val')
  File "D:\sulisha\HGT-DGL-master\PRGC-main\PRGC-main\evaluate.py", line 92, in evaluate
    ex_params=ex_params)
ValueError: not enough values to unpack (expected 4, got 3)
请问一下怎么解决
